version: '3'

services:
  sql:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sangsu
      POSTGRES_PASSWORD: sangsu
      POSTGRES_DB: otogetodo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/dev/pgdata:/var/lib/postgresql/data